// Generated by CoffeeScript 1.6.3
(function() {
  var $, App, Glue, Gui, Server, UseCase, app,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _.defaults(this, {
    Before: function(object, methodName, adviseMethod) {
      return YouAreDaBomb(object, methodName).before(adviseMethod);
    },
    BeforeAnyCallback: function(object, methodName, adviseMethod) {
      return YouAreDaBomb(object, methodName).beforeAnyCallback(adviseMethod);
    },
    After: function(object, methodName, adviseMethod) {
      return YouAreDaBomb(object, methodName).after(adviseMethod);
    },
    Around: function(object, methodName, adviseMethod) {
      return YouAreDaBomb(object, methodName).around(adviseMethod);
    }
  });

  $ = jQuery;

  Server = (function() {
    function Server() {}

    Server.prototype.take_data = function() {
      return $.get('http://0.0.0.0:3000/name_list', function(data) {
        return $(".main").append(data);
      });
    };

    return Server;

  })();

  UseCase = (function() {
    function UseCase() {
      this.writeNames = __bind(this.writeNames, this);
      this.names = ["Anette", "Henry", "Tarja", "Mia", "Callin", "Pauli"];
    }

    UseCase.prototype.start = function() {
      console.log("hello");
      return this.writeNames(this.names);
    };

    UseCase.prototype.writeNames = function(names) {};

    return UseCase;

  })();

  Gui = (function() {
    function Gui() {
      this.showNames = __bind(this.showNames, this);
      this._createElementFor = __bind(this._createElementFor, this);
    }

    Gui.prototype._createElementFor = function(templateId, data) {
      var element, html, source, template;
      source = $(templateId).html();
      template = Handlebars.compile(source);
      html = template(data);
      return element = $(html);
    };

    Gui.prototype.showNames = function(names) {
      var element;
      element = this._createElementFor("#show-names-template", {
        names: names
      });
      return $(".main").append(element);
    };

    return Gui;

  })();

  Glue = (function() {
    function Glue(useCase, gui) {
      var _this = this;
      this.useCase = useCase;
      this.gui = gui;
      After(this.useCase, "writeNames", function(names) {
        return _this.gui.showNames(names);
      });
    }

    return Glue;

  })();

  App = (function() {
    function App() {
      var glue, gui, server, usecase;
      console.log("hello");
      server = new Server();
      usecase = new UseCase();
      gui = new Gui();
      glue = new Glue(usecase, gui);
      usecase.start();
      server.take_data();
    }

    return App;

  })();

  app = new App();

}).call(this);
